config/routes.rb
EpubSearch::Application.routes.draw do
  resources :contents, only: [:index]
  resources :books, only: [:index, :show, :new, :create, :destroy]
  resources :users, only: [:new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :author, :filename, :location, :title
  mount_uploader :location, EpubUploader

  belongs_to :user
  has_many :contents, dependent: :destroy

  validates :author, :filename, :location, :title, :user_id, presence: true
end

app/models/content.rb
class Content < ActiveRecord::Base
  attr_accessible :book_id, :content

  belongs_to :book
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password
  attr_accessor :password

  has_many :books, dependent: :destroy

  def authenticate(uncrypted_password)
    BCrypt::Password.new(password_digest) == uncrypted_password
  end

  before_save do
    self.password_digest = BCrypt::Password.create(password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user

  private

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by_id(session[:user_id])
    end
  end
  helper_method :current_user

  def authenticate_user
    redirect_to [:new, :session] unless current_user
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # GET /books
  # GET /books.json
  def index
    @books = Book.where(:user_id => current_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find_by_id_and_user_id!(params[:id], current_user.id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
      format.epub { send_file @book.location.url, filename: @book.filename, dispositioin: 'attachment', type: 'application/epub+zip' }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # POST /books
  # POST /books.json
  def create
    file = params[:book].delete(:file)
    book_info = EPUB::Parser.parse(file.tempfile).package.metadata
    @book = Book.new(params[:book])
    @book.title = book_info.title
    @book.author = book_info.creators.join
    @book.filename = File.basename(file.original_filename)
    @book.location = file

    respond_to do |format|
      if current_user.books << @book
        Resque.enqueue EpubRegistrar, @book.id
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    # TODO: add key for [id, user_id] to books table
    @book = Book.find_by_id_and_user_id!(params[:id], current_user.id)
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  # GET /contents
  # GET /contents.json
  def index
    @q = params[:q]
    if @q.blank?
      @contents = []
    else
      @contents = Content.joins(:book).where(books: {user_id: current_user.id})\
        .where(['MATCH (content) AGAINST (?)', @q])\
        .order(:contents => ['MATCH (content) AGAINST (?) DESC', @q])
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contents }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authenticate_user

  def create
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to :books
    else
      render :new
    end
  end

  def destroy
    session.delete :user_id
    redirect_to [:new, :session]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :file %><br />
    <%= f.file_field :file %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Listing books</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Filename</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @books.each do |book| %>
  <tr>
    <td><%= book.title %></td>
    <td><%= book.author %></td>
    <td><%= book.filename %></td>
    <td><%= link_to 'Show', book %></td>
    <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @book.title %>
</p>

<p>
  <b>Author:</b>
  <%= @book.author %>
</p>

<p>
  <b>Filename:</b>
  <%= @book.filename %>
</p>


<%= link_to 'Back', books_path %>

app/views/contents/_form.html.erb
<%= form_for(@content) do |f| %>
  <% if @content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% @content.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :book_id %><br />
    <%= f.number_field :book_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<h1>Editing content</h1>

<%= render 'form' %>

<%= link_to 'Show', @content %> |
<%= link_to 'Back', contents_path %>

app/views/contents/index.html.erb
<h1>Listing contents</h1>

<%= form_tag(:contents, :method => :get) do %>
<p><%= text_field_tag :q, @q %><%= submit_tag 'search' %></p>
<% end %>

<table>
  <tr>
    <th>Book</th>
    <th>Content</th>
  </tr>

<% @contents.each do |content| %>
  <tr>
    <td><%= link_to content.book.title, book_path(content.book, format: 'epub') %></td>
    <td><%= content.content %></td>
  </tr>
<% end %>
</table>

<br />

app/views/contents/new.html.erb
<h1>New content</h1>

<%= render 'form' %>

<%= link_to 'Back', contents_path %>

app/views/contents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @content.content %>
</p>

<p>
  <b>Book:</b>
  <%= @content.book_id %>
</p>


<%= link_to 'Edit', edit_content_path(@content) %> |
<%= link_to 'Back', contents_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EpubSearch</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= link_to 'logout', :session, method: :delete %>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br />
    <%= f.text_field :password_digest %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Password digest</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.password_digest %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Password digest:</b>
  <%= @user.password_digest %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>